### ISSUE TITLE
CCK: DC Postmortem Checklist

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-dc#171]
- [x]  **1. Schedule the meeting** (Date: 02/14/2018)
  - [x] Require the entire sim team to participate, and optionally anyone else who had a significant involvement. Have the meeting as soon as possible after the sim is released, so that experiences are still fresh in everyone's mind. Allow sufficient time for the meeting, 1.5-2 hours.

- [x]  **2. Enlist a meeting moderator** (@oliver-phet)
  - [x] The moderator's job is to make sure the meeting runs efficiently, stays on point, and focuses on constructive (but not overly negative) critcism. The moderator can be someone not on the sim team, or in many cases the Development Coordinator. The moderator also documents the important points of the meeting.

- [x]  **3. Create github postmortem issue and postmortem google doc**
  - [x] Create a github issue in the repository of the sim for which the postmortem is occurring. This checklist will should be copied into the issue.
  - [x] Create a postmortem google doc for the sim and set phet-docs as the owner. This google doc should live within the appropriate sim folder on google drive.

- [x] **4. Two successes and two improvements**
  - [x] Require participants to bring a list of no more than 2 items that were done well during the project and no more than 2 items that could be improved upon. Limiting to 2 requires people to think critically about their experience.

- [x]  **5. Identifying the top five**
  - [x] At the meeting, start by going around the room and having each person present their items (successes, then improvements). Make a list of these items, and note duplicates. Based on popularity, identify the top 5 success items and the top 5 items that need improvement.
  - [x] Discuss the 5 success items first. Identify specific things that can be applied to future sims. Celebrate, pat each other on the back. Then move on to the harder part.
  - [x] Discuss the 5 improvement items. Try to avoid getting personal. Discuss what was learned, and identify specific things that can be done to prevent these problems in the future. If anything needs more investigation, assign to specific individuals.

- [x]  **6. Modifications to Look & Feel** 
  - [x] Identify modifications to the PhET Look-&-Feel Guidelines. If applicable, based on what we learned during development of this sim, suggest revisions to the guidelines.
  * [HTML5 Look and Feel](https://docs.google.com/document/d/1Fg4E6VNMsnId7CjsyqHKnZeIoQ4N-5ezM9PTkj7N3PM/edit)
  * [HTML5 Sim Design Elements
](https://docs.google.com/document/d/1rpp0vT7-bGUs_5tZP_77-HM8PnaGbIDQ5DGNygX5CBo/edit)
- [x]  **7. Sim checklist** 
  - [x] Review the "Sim checklist" (under development). Will be a "living" issue for each sim repository

- [x]  **8. Action items** 
  - [x]  Note important items in the postmortem github issue, and create issues for any tasks the require action (such as updating documents, leftover "todo's", etc. 

- [x]  **9. Take home messages** 
  - [x] From the top 5 successes/improvements, decide what are the "take home messages" that would be useful to note in the future, and add these to the [HTML5 Postmortem Take Home Messages](https://docs.google.com/document/d/1hayLX0FbhYqGao-5xizAFU9kVBzqrW_RVX88Wk_C_Lc/edit#heading=h.krbf2d24bpav) google doc
  - [x] Report out at status meeting

**Comment by arouinfar** [comment]
For future discussion:
* Dust off Look & Feel docs in future website/keyboard nav meeting
* Strategy for dealing with sims with "common" repo 
* Releasing prototypes prior to publication

@ariel-phet should we leave this is open until we've discussed the above items?

**Comment by ariel-phet** [comment]
@arouinfar yes, for the moment, I will take it from here.

**Comment by ariel-phet** [comment]
Separate issues have been made, and discussions have taken place for the common repo question. Closing
