### ISSUE TITLE
Items to Include in Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-dc#41]
- [x] https://github.com/phetsims/circuit-construction-kit-common/issues/294 - Voltmeter probes read anywhere within the vertex. 
- [x] https://github.com/phetsims/circuit-construction-kit-common/issues/147 - Electron animation is paused when dragging circuit component or vertex.
- [x] Non-contact ammeters exist (e.g. AC/DC current clamp) though are typically used to measure ~1-1000 amps.
- [x] https://github.com/phetsims/circuit-construction-kit-dc/issues/27 - Non-contact ammeter reads over the bulb.
- [x] <s>https://github.com/phetsims/circuit-construction-kit-common/issues/273 - Path of electrons in schematic bulb</s>
- [x] https://github.com/phetsims/circuit-construction-kit-common/issues/245 - Limits of an ideal battery
- [x]  https://github.com/phetsims/circuit-construction-kit-common/issues/290#issuecomment-307160685 - Precision limits
- [x] Pencil = graphite
- [x] https://github.com/phetsims/circuit-construction-kit-dc/issues/79 - Sensors read over lifelike boundaries
- [x] <s>https://github.com/phetsims/circuit-construction-kit-common/issues/281#issuecomment-315920873 - Current bunches up if wire length is exactly zero.</s>
- [x] https://github.com/phetsims/circuit-construction-kit-dc/issues/98 - Resistor tolerance 
- [x] https://github.com/phetsims/circuit-construction-kit-dc/issues/125 - Wires are not ideal (resistivity != 0) and long wires can effect the current in a circuit.
- [x] Batteries with internal resistance are modeled as a battery+resistor. When in a complete circuit the voltage drop across the battery will be zero (unless wire resistivity is high).
- [x] Delete key can delete components and cut vertices.
- [x]  Both the electrons and conventional current representations are "cartoon" representations and do not perfectly model the current in the circuit. Their speed and density give an approximate visual but should not be taken literally.
- [x] Explanation of Virtual Lab flavor.
- [x] Light bulb is Ohmic.

From legacy tips:
- [x] Fire denotes a short circuit or very high current
- [x] If the current is high and the blue dots for the electrons cannot be drawn fast enough, the sim changes speed and this displays
- [x] When you change the Wire Resistivity, the amount of resistance will vary with the length of the wire. So to find the resistance value for any wire, read both the current and voltage and use Ohm’s Law R=V/I

**Comment by arouinfar** [comment]
Everything in https://github.com/phetsims/circuit-construction-kit-dc/issues/41#issue-226421495 has been documented in the Tips, so closing.
