### ISSUE TITLE
Development Checklist

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#50]
- [x] receive artwork for grab bag
- [x] Sim is basically feature complete
- [x] memory leaks and garbage collection
- [x] @samreid should go through the code review checklist, see #53 
- [x] performance with @jonathanolson, first meeting scheduled for June 14
- [x] Testing a version for AAPT
- [x] Address known issues, cleaning up TODOs
- [x] Make sure fuzz test is passing, see #108 
- [x] developer testing, see https://github.com/phetsims/circuit-construction-kit-dc/issues/109
- [x] Design team testing
- [x] some initial dev testing QA, see https://github.com/phetsims/circuit-construction-kit-dc/issues/47 and https://github.com/phetsims/QA/issues/33
- [x] publish a new "prototype" version, see https://github.com/phetsims/circuit-construction-kit-dc/issues/46
- [x] code review by @jonathanolson, see https://github.com/phetsims/circuit-construction-kit-common/issues/317
- [x] addressing issues raised during code review
- [ ] another dev test, see https://github.com/phetsims/QA/issues/48
- [ ] QA and address discovered issues

**Comment by samreid** [comment]
@ariel-phet I would like to confirm the ordering of initial Dev QA testing and initial code review.  Do you want to do dev testing first or code review first?

**Comment by ariel-phet** [comment]
@samreid yes, dev testing should occur before code review. Dev testing may well reveal issues that require refactoring/changes. We like to ideally review code that is in a stable state, reasonably bug free, and unlikely to undergo many changes except for those raised by the review.

**Comment by samreid** [comment]
I published http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.160/circuit-construction-kit-dc_en.html and will test it on a few browsers before giving to the QA team.

**Comment by samreid** [comment]
Since we are on dev testing and hopefully going into RC soon, this issue has served its usefulness, closing.
